### ISSUE TITLE
Add PureScript sources of test CoreFn json strings

### ISSUE THREAD

**Issue by felixSchl** [paulyoung/purescript-corefn#56]
Would be great to have the PureScript sources of the various corefn json strings occurring in the test suite.

**Comment by paulyoung** [comment]
I believe these were taken directly from https://github.com/purescript/purescript/blob/c19a79285c5697b59c46803483b41ffeaa5cd7b0/tests/TestCoreFn.hs

**Comment by felixSchl** [comment]
Thanks for the link!
